packageExtensions:
  # "@parcel/cache@*":
  #   dependencies:
  #     "@parcel/core": "*"
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": "*"
  # "@parcel/package-manager@*":
  #   dependencies:
  #     "@parcel/core": "*"
  # "@parcel/workers@*":
  #   dependencies:
  #     "@parcel/core": "*"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
